# Generated by Django 6.0.4 on 2026-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='For dropdown: list of [value, label] pairs', null=True),
        ),
    ]
