# Generated by Django 6.0.4 on 2026-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_asset_company_assetcategory_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned To'),
        ),
    ]
