# Generated by Django 6.0.4 on 2026-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_asset_assigned_to_asset_assigned_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='name',
            field=models.CharField(help_text='Field identifier (used as key in JSON)', max_length=100),
        ),
    ]
